/*
  # BarberTech Pro - Tabelas Principais
  
  Criação das tabelas principais para o sistema de agendamento
*/

CREATE TABLE IF NOT EXISTS organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  logo_url TEXT,
  address_street TEXT,
  address_number TEXT,
  address_city TEXT,
  address_state TEXT,
  address_zip TEXT,
  phone TEXT,
  email TEXT,
  whatsapp_number TEXT,
  timezone TEXT DEFAULT 'America/Sao_Paulo',
  currency TEXT DEFAULT 'BRL',
  booking_advance_days INT DEFAULT 30,
  booking_min_notice_hours INT DEFAULT 2,
  stripe_account_id TEXT,
  pix_key TEXT,
  default_split_percentage DECIMAL(5,2) DEFAULT 70.00,
  no_show_policy JSONB DEFAULT '{"new_client": "full_prepay", "low_score": "full_prepay", "regular": "30_percent", "vip": "optional"}'::jsonb,
  plan_tier TEXT DEFAULT 'growth' CHECK (plan_tier IN ('mvp', 'growth', 'premium')),
  plan_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('owner', 'barber', 'receptionist', 'manager')),
  full_name TEXT NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  email TEXT,
  bio TEXT,
  specialties TEXT[],
  rating DECIMAL(3,2) DEFAULT 5.00,
  total_reviews INT DEFAULT 0,
  custom_split_percentage DECIMAL(5,2),
  working_hours JSONB DEFAULT '{"monday": {"enabled": true, "slots": [{"start": "09:00", "end": "18:00"}]}, "tuesday": {"enabled": true, "slots": [{"start": "09:00", "end": "18:00"}]}, "wednesday": {"enabled": true, "slots": [{"start": "09:00", "end": "18:00"}]}, "thursday": {"enabled": true, "slots": [{"start": "09:00", "end": "18:00"}]}, "friday": {"enabled": true, "slots": [{"start": "09:00", "end": "18:00"}]}, "saturday": {"enabled": true, "slots": [{"start": "09:00", "end": "15:00"}]}, "sunday": {"enabled": false, "slots": []}}'::jsonb,
  is_active BOOLEAN DEFAULT true,
  is_accepting_bookings BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(organization_id, email)
);

CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  birth_date DATE,
  segment TEXT DEFAULT 'regular' CHECK (segment IN ('new', 'regular', 'vip', 'at_risk', 'churned')),
  tags TEXT[] DEFAULT '{}',
  trust_score INT DEFAULT 500,
  total_bookings INT DEFAULT 0,
  completed_bookings INT DEFAULT 0,
  no_show_count INT DEFAULT 0,
  cancelled_count INT DEFAULT 0,
  total_spent DECIMAL(10,2) DEFAULT 0,
  lifetime_value DECIMAL(10,2) DEFAULT 0,
  average_ticket DECIMAL(10,2) DEFAULT 0,
  preferred_barber_id UUID REFERENCES users(id) ON DELETE SET NULL,
  preferred_time_of_day TEXT,
  notes TEXT,
  points INT DEFAULT 0,
  cashback_balance DECIMAL(10,2) DEFAULT 0,
  subscription_status TEXT CHECK (subscription_status IN ('active', 'paused', 'cancelled', 'expired')),
  subscription_starts_at TIMESTAMPTZ,
  subscription_ends_at TIMESTAMPTZ,
  subscription_credits_remaining INT DEFAULT 0,
  is_blocked BOOLEAN DEFAULT false,
  blocked_reason TEXT,
  blocked_until TIMESTAMPTZ,
  accepts_marketing BOOLEAN DEFAULT true,
  accepts_whatsapp BOOLEAN DEFAULT true,
  first_visit_at TIMESTAMPTZ,
  last_visit_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(organization_id, phone)
);

CREATE TABLE IF NOT EXISTS services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  price DECIMAL(10,2) NOT NULL,
  duration_minutes INT NOT NULL,
  category TEXT CHECK (category IN ('cut', 'beard', 'combo', 'treatment', 'other')),
  is_active BOOLEAN DEFAULT true,
  requires_prepayment BOOLEAN DEFAULT false,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS subscription_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  billing_period TEXT NOT NULL CHECK (billing_period IN ('monthly', 'quarterly', 'yearly')),
  credits_per_period INT NOT NULL,
  rollover_unused_credits BOOLEAN DEFAULT false,
  discount_on_products_percentage DECIMAL(5,2) DEFAULT 0,
  priority_booking BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  barber_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  scheduled_at TIMESTAMPTZ NOT NULL,
  duration_minutes INT NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'checked_in', 'in_progress', 'completed', 'no_show', 'cancelled')),
  confirmed_at TIMESTAMPTZ,
  confirmation_count INT DEFAULT 0,
  checked_in_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  cancelled_by UUID REFERENCES users(id) ON DELETE SET NULL,
  cancellation_reason TEXT,
  service_price DECIMAL(10,2) NOT NULL,
  prepayment_required BOOLEAN DEFAULT false,
  prepayment_amount DECIMAL(10,2),
  prepayment_status TEXT CHECK (prepayment_status IN ('not_required', 'pending', 'paid', 'refunded')),
  no_show_fee DECIMAL(10,2),
  no_show_charged BOOLEAN DEFAULT false,
  client_notes TEXT,
  barber_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  booking_id UUID REFERENCES bookings(id) ON DELETE SET NULL,
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  currency TEXT DEFAULT 'BRL',
  payment_type TEXT NOT NULL CHECK (payment_type IN ('service', 'subscription', 'prepayment', 'no_show_fee', 'product')),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('pix', 'credit_card', 'debit_card', 'cash', 'transfer')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'succeeded', 'failed', 'refunded', 'partially_refunded')),
  gateway TEXT CHECK (gateway IN ('stripe', 'mercadopago', 'manual')),
  gateway_payment_id TEXT,
  gateway_payment_url TEXT,
  split_barber_amount DECIMAL(10,2),
  split_barber_percentage DECIMAL(5,2),
  split_barber_paid BOOLEAN DEFAULT false,
  split_barber_paid_at TIMESTAMPTZ,
  refunded_amount DECIMAL(10,2),
  refunded_at TIMESTAMPTZ,
  refund_reason TEXT,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS waitlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  service_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  barber_id UUID REFERENCES users(id) ON DELETE CASCADE,
  preferred_dates DATE[] NOT NULL,
  preferred_times TEXT[] NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'matched', 'expired', 'cancelled')),
  matched_booking_id UUID REFERENCES bookings(id) ON DELETE SET NULL,
  matched_at TIMESTAMPTZ,
  last_notified_at TIMESTAMPTZ,
  notification_count INT DEFAULT 0,
  expires_at TIMESTAMPTZ DEFAULT (now() + INTERVAL '30 days'),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  campaign_type TEXT NOT NULL CHECK (campaign_type IN ('reactivation', 'upsell', 'birthday', 'loyalty_reward', 'review_request', 'appointment_reminder', 'custom')),
  target_segment JSONB NOT NULL,
  message_template TEXT NOT NULL,
  message_variables JSONB,
  channel TEXT NOT NULL CHECK (channel IN ('whatsapp', 'email', 'sms', 'push')),
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('immediate', 'scheduled', 'event_based')),
  scheduled_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'paused', 'completed')),
  total_sent INT DEFAULT 0,
  total_delivered INT DEFAULT 0,
  total_opened INT DEFAULT 0,
  total_clicked INT DEFAULT 0,
  total_converted INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS daily_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  total_bookings INT DEFAULT 0,
  completed_bookings INT DEFAULT 0,
  no_show_bookings INT DEFAULT 0,
  cancelled_bookings INT DEFAULT 0,
  no_show_rate DECIMAL(5,2) DEFAULT 0,
  completion_rate DECIMAL(5,2) DEFAULT 0,
  occupancy_rate DECIMAL(5,2) DEFAULT 0,
  revenue DECIMAL(10,2) DEFAULT 0,
  prepayments DECIMAL(10,2) DEFAULT 0,
  no_show_fees_collected DECIMAL(10,2) DEFAULT 0,
  refunds DECIMAL(10,2) DEFAULT 0,
  average_ticket DECIMAL(10,2) DEFAULT 0,
  new_clients INT DEFAULT 0,
  returning_clients INT DEFAULT 0,
  estimated_lost_revenue_prevented DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(organization_id, date)
);
